### ISSUE TITLE
unreadable noise signals in the fma_small subset

### ISSUE THREAD

**Issue by ChangLee0903** [Lamomal/MultiSV#1]
Dear MultiSV members,

I just noticed that there are some unused noise signals that cannot be loaded by torchaudio and librosa, such as 'fma_small/108/108925', 'fma_small/099/099134', and 'fma_small/133/133297'. I think there might be some broken files in the noise dataset?

best regards,
Chi-Chang Lee

**Comment by Lamomal** [comment]
Dear Chi-Chang,

Thank you for bringing this up. Indeed, the noise files you mentioned do not contain any audio. It is a known issue of the FMA dataset. For reference, please see [FMA wiki](https://github.com/mdeff/fma/wiki) and [a related issue](https://github.com/mdeff/fma/issues/44). In line with your comment, MultiSV users might encounter warnings during data preparation related to these files (which can be safely ignored). Even if the FMA small dataset is downloaded correctly (as indicated by the `create_training_data.sh` script, which compares checksums), the erroneous files will cause the following warnings during the conversion to wav:
`WARNING: conversion failed for: <output_dir>/noises_training/fma_small/108/108925.mp3`
`WARNING: conversion failed for: <output_dir>/noises_training/fma_small/099/099134.mp3`
`WARNING: conversion failed for: <output_dir>/noises_training/fma_small/133/133297.mp3`

Since MultiSV does not use these three files, they do not pose an issue for the corpus.

Best,
Ladislav
